    // --- debug hooks (appended by tests/harness.js, never shipped) ---
    window._dbg = function(){ return { state: state, level: level, score: score, bugs: bugs }; };
    window._dbgSpider = function(){ return spider; };
    window._dbgTarget = function(){ return target; };
    window._dbgStrands = function(){ return strands; };
    window._dbgHubs = function(){ return hubs; };
    window._dbgCrossings = function(){ return crossings; };
    window._dbgWebSilk = function(v){ webSilk = v; };
    window._dbgAuto = function(){ return { on: autoWeb, edges: autoEdges ? autoEdges.length : 0, repair: autoRepair }; };
    window._dbgPushStrand = function(x1,y1,x2,y2){ strands.push({x1:x1,y1:y1,x2:x2,y2:y2,decayAt:0,born:now()}); recalcSupport(); };
    window._dbgClearBugs = function(){ for(var i=bugs.length-1;i>=0;i--){ bugs[i].dead=true; bugs.splice(i,1); } };
    window._dbgHoldStill = function(){ return holdStill; };
    window._dbgBeatBoss = function(k){ bossesBeaten[k] = true; };
    window._dbgChargeBrood = function(){ broodMeter = BROOD_MAX; eggReady = true; };
    window._dbgTut = function(){ return { tutorial: tutorial, step: tutStep, n: TUT_STEPS.length, msg: TUT_STEPS[tutStep] ? TUT_STEPS[tutStep].msg() : '', mark: tutMark }; };
    window._dbgTutMsgs = function(){ return TUT_STEPS.map(function(s){ return s.msg(); }); };
    window._dbgRage = function(){ return { meter: rageMeter, until: rageUntil, active: rageActive(), max: RAGE_MAX }; };
    window._dbgChargeRage = function(){ rageMeter = RAGE_MAX; };
    window._dbgScores = function(){ return scores; };
    window._dbgRecordScore = function(s,lv){ return recordScore(s,lv); };
    window._dbgState = function(){ return state; };
    window._dbgSetScoreVars = function(s,lv){ score = s; level = lv; };
    window._dbgGameOver = function(){ gameOver(); };
    window._dbgGems = function(){ return gems; };
    window._dbgSpawnGem = function(x,y,k){ spawnGem(x,y,k); };
    window._dbgPushGem = function(x,y,k){ gems.push({x:x,y:y,k:k,born:now()}); };
    window._dbgQuota = function(){ return { quota: quota, caught: caught, level: level }; };
    window._dbgSetCaught = function(v){ caught = v; };
    window._dbgSetSwarm = function(v){ swarmAt = v; };
    window._dbgCatch = function(b,w){ catchBug(b,w); };
    window._dbgTypes = TYPES;
    window._dbgVars = function(){ return { silk: silk, webSilk: webSilk, hearts: hearts, score: score, floats: floats }; };
    window._dbgSetHearts = function(v){ hearts = v; };
    window._dbgShotMode = function(){ return { mode: shotModeActive(), until: shotModeUntil }; };
    window._dbgGrantMode = function(k){ grantShotMode(k); };
    window._dbgShots = function(){ return shots; };
    window._dbgShoot = function(x,y){ shootWeb(x,y); };
    window._dbgSetSilk = function(v){ silk = v; };
    window._dbgSetBombs = function(v){ bombs = v; };
    window._dbgUseBomb = function(){ useBomb(); };
    window._dbgBugs = function(){ return bugs; };
    window._dbgSpawnAt = function(k,x,y){ spawnBug(k); var b = bugs[bugs.length-1]; b.x = x; b.y = y; b.vx = 0; b.vy = 0; return b; };
    window._dbgWebBug = function(b){ webBug(b); };
    window._dbgSinks = SINKS;
    window._dbgUpg = UPG;
    window._dbgBeams = function(){ return beams; };
    window._dbgTheme = function(){ return bgTheme; };
    window._dbgSetTheme = function(m){ setTheme(m); };
    window._dbgThemes = THEMES;
    window._dbgMus = function(){ return { song: MUS.song, on: musicOn, step: MUS.step }; };
    window._dbgSongs = SONGS;
    window._dbgAnimKinds = function(){ return themeAnim.map(function(a){ return a.k; }); };
    window._dbgAnim = function(){ return themeAnim; };
    window._dbgCombo = function(){ return { n: comboN, until: comboUntil }; };
    window._dbgMusMod = function(){ return musMod(); };
    window._dbgSetSwarmMusic = function(){ lastSwarmAt = now(); };
    window._dbgSilkTier = function(st){ return silkTier(st, now()); };
    window._dbgSetStat = function(k, v){ S[k] = v; };
    window._dbgBreak = function(i){ breakStrand(strands[i]); };
    window._dbgFallen = function(){ return fallenLog; };
    window._dbgStrandCost = function(len){ return strandCost(len); };
    window._dbgSurge = function(){ return surgeUntil; };
    window._dbgRun = function(){ return { combo: runMaxCombo, bosses: runBossKills, strands: runMaxStrands, gilded: runMaxGilded, weapons: Object.keys(runWeapons).length }; };
